from typing import Optional, Any
from pydantic import BaseModel, Field


class VoiceTurnRequest(BaseModel):
    """Voice turn request when submitting text or base64 audio directly."""
    turn_id: Optional[str] = Field(None, description="Unique turn ID for duplicate request prevention")
    audio_base64: Optional[str] = Field(None, description="Base64 encoded audio bytes (WAV, WebM, MP3)")
    audio_format: str = Field("webm", description="Audio format (webm, wav, mp3, ogg)")
    text: Optional[str] = Field(None, description="Direct text input in any Indian language or English for testing")
    language_code: Optional[str] = Field(None, description="Override or specified language code (e.g. te-IN, hi-IN)")


class VoiceTurnResponse(BaseModel):
    """Unified voice turn response preserving original user transcript, backend English, and native audio."""
    conversation_id: str
    task_id: Optional[str] = None
    turn_id: Optional[str] = None
    
    # User side
    original_user_text: str = Field(..., description="Transcript in the language the user actually spoke")
    user_language: str = Field(..., description="Detected or configured BCP-47 language code (e.g. te-IN)")
    backend_english_text: str = Field(..., description="English representation sent to the action assistant backend")
    
    # Assistant side
    assistant_english_text: str = Field(..., description="Original English response generated by the existing backend")
    assistant_localized_text: str = Field(..., description="Response translated into user's language")
    task_state: str = Field("IN_PROGRESS", description="Current state of the booking task")
    
    # Audio
    audio_base64: Optional[str] = Field(None, description="Base64-encoded Bulbul v3 TTS audio in user's language")
    audio_format: str = Field("wav", description="Audio format of the synthesized response")
    voice_status: str = Field("success", description="Status of the voice layer processing (success, partial, tts_fallback)")
